-- cf#520: per-route authorization. `api_tokens` said WHO a credential belongs to and nothing about
-- WHAT it may do, so every named token was operator-equivalent -- a consumer token could call
-- POST /api/storage/reconcile, which rewrites an estate-wide ledger (cf#516).
--
-- SCHEMA migration, NOT a data migration. Nothing is in production; all four live tokens are
-- reissued with an explicit scope, so this column does not have to arrive at a safe state by
-- inference. The DEFAULT exists only because SQLite requires a non-NULL default when ADD COLUMN
-- carries NOT NULL -- it is not a compatibility affordance and nothing should be built on it.
--
-- ITS VALUE IS DELIBERATE AND IT HAS A CONSEQUENCE THE OPERATOR MUST SEQUENCE: 'consumer' is the
-- least privilege, so applying this migration DOWNGRADES every existing named token to consumer
-- until it is reissued. That is the safe direction (a consumer token that needed more 401s loudly;
-- an operator default would leave the hole open under a new name), but it means the reissue has to
-- happen with the tag that applies this migration, not after it. Migrations apply in the DEPLOY
-- job on a version tag, so merging this is inert -- tagging is the moment it lands.
--
-- THE VALUES LIVE IN migrations/manual/0021_set_live_token_scopes.sql AND MUST NOT BE MOVED HERE.
-- Setting the four estate scopes in THIS file is the obvious shortcut and it is a security defect:
-- top-level migrations/*.sql are bundled into the studio release (scripts/build-studio-release.ts:209)
-- and replayed into every TENANT D1 (vivijure-control-plane src/provisioner.ts:653, "the SAME
-- migration files the studio ships, applied only where missing"). 0009 creates api_tokens in every
-- tenant too, `name` is its PRIMARY KEY, and `mint` accepts any [a-z0-9][a-z0-9_-]{0,63} -- so
-- `conrad` and `joan` are names a TENANT can legitimately choose. A name-matching UPDATE here
-- silently promotes that tenant's own token to operator: cf#520's hole, reopened under a name, in
-- the one file whose header forbids exactly that.
--
-- The migrations-gate CANNOT catch this. It replays against a fresh local D1 where those rows do
-- not exist, so the UPDATE matches zero rows and the gate is structurally incapable of going red.
-- Its pass is not evidence. migrations/manual/ is operator-run and never bundled (that same
-- build-studio-release comment says so, and readdirSync there is non-recursive), which is why the
-- values live there and are applied by hand against the estate DB alone.
--
-- The CHECK constraint is not retroactive: SQLite does not re-evaluate it for rows that predate
-- the ALTER. src/auth-gate.ts therefore re-validates every value it reads and fails CLOSED on
-- anything outside the union, which is the guard that actually holds.
ALTER TABLE api_tokens
  ADD COLUMN scope TEXT NOT NULL DEFAULT 'consumer'
  CHECK (scope IN ('operator', 'consumer'));
