#!/usr/bin/env bash
# Replace host orchestration duplicates with thin re-exports into @skyphusion-labs/vivijure-core.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PKG="@skyphusion-labs/vivijure-core"

reexport() {
  local rel="$1"
  local core_path="${2:-${rel%.ts}}"
  local dest="$ROOT/src/$rel"
  mkdir -p "$(dirname "$dest")"
  cat >"$dest" <<EOF
// Host shim: orchestration lives in ${PKG}.
export * from "${PKG}/${core_path}";
EOF
}

reexport "modules/types.ts" "modules/types"
reexport "modules/conformance.ts" "modules/conformance"
reexport "modules/registry.ts" "modules/registry"
reexport "modules/render-pipeline.ts" "modules/render-pipeline"
reexport "film-model.ts"
reexport "clip-job-model.ts"
reexport "storyboard-ids.ts"
reexport "film-orchestrator.ts"
reexport "render-orchestrator.ts"
reexport "clip-validate.ts"
reexport "render-module-config.ts"
reexport "runpod-types.ts"
reexport "clip-content-validate.ts"
reexport "cast-db.ts"
reexport "storyboard-projects-db.ts"
reexport "renders-db.ts"
reexport "render-log.ts"
reexport "public-id.ts"
reexport "db-env.ts"
reexport "d1-retry.ts"
reexport "film-advance-lease.ts"
reexport "bundle-assembler.ts"
reexport "bundle-durations.ts"
reexport "storyboard-validate.ts"
reexport "planner-yaml.ts"
# tar.ts stays host-local (cast-bundle uses legacy tar helpers not in core)
reexport "key-safety.ts"
reexport "lora-keys.ts"
reexport "preflight.ts"
reexport "planner-prompt.ts"
reexport "output-extract.ts"
reexport "scatter-orchestrator.ts"
reexport "scatter-orchestrator-types.ts"
reexport "scatter.ts"
reexport "scatter-notify.ts"
reexport "beat-analyze.ts"
reexport "audio-stage.ts"
reexport "audio-routing.ts"
reexport "operator-config.ts"
reexport "dialogue-lines.ts"
reexport "cast-loras.ts"
reexport "cast-lora-train.ts"
reexport "lora-bundle.ts"
reexport "runpod-submit.ts"
reexport "render-sweep.ts"
reexport "render-adopt.ts"
reexport "render-mux.ts"
reexport "clip-provenance.ts"
reexport "bundle-storyboard.ts"
reexport "captions.ts"
reexport "srt.ts"
reexport "finish-hash.ts"
reexport "voices.ts"
reexport "secret-store.ts"

echo "core re-exports written under src/"
